[projects."/home/lucas/workplace/personal"]
trust_level = "trusted"

model_provider="openrouter"
model="openai/gpt-5"

[model_providers.openrouter]
name="openrouter"
base_url="https://openrouter.ai/api/v1"
env_key="OPENROUTER_API_KEY"